Portfolio webiste 2
den-cloud/Portfolio_Website pull request #4
Opened 2021-08-16 21:13 UTC by den-cloud

2021-08-17 19:44 UTC, karvel-code requested changes
Hi @den-cloud , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- Your linter checks pass successfully.

## Required Changes ♻️
_Check the comments under the review._

- Please ensure you follow the design provided in the Figma design for the contact form section:

- [ ] Check on the margins between the different features of the page.
- [ ] Also, check on the font required according to the design especially for the placeholder texts.
- [ ] Ensure to use the right colours required. For instance, the colour for the `Contact me` title is not black as done according to your design.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ] Please enhance the responsiveness of your site. The content is not positioned in the right manner for some mobile sizes.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-17 19:44 UTC, karvel-code commented on index.html
> +        <form action="#" method="POST" class="contact-form"></form>
- [ ] Please ensure that you add the formspree link as the value to the action attribute. The link should be similar to: `https://formspree.io/f/{form_id}`.
- [ ]  Ensure that your input tags are wrapped inside the form tags. The `</form>` closing tag should be after the button code(after line 212 and before line 213).

2021-08-17 19:44 UTC, karvel-code commented on index.html
> +        <button type="submit" id="contact-btn">Get In Touch</button>
- [ ] Your form is supposed to submit valid data successfully. However, this is not the case with your form. Please work on that issue.

2021-08-17 19:44 UTC, karvel-code commented on index.html
> +        <input type="text" name="_name" placeholder="Name" class="form-field" required>
- [ ] Please ensure to add the attribute `maxlength = "30" ` for the name input tag. This is so as to add and improve on the validations for your form.

2021-08-17 19:44 UTC, karvel-code commented on index.html
> +            class="form-field contact-message"></textarea>
- [ ] Please ensure to add the `required` attribute for the message input. This is in order to activate its validation on submit.

2021-08-17 19:44 UTC, karvel-code commented on index.html
> +        <button type="submit" id="contact-btn">Get In Touch</button>
- [ ] Please ensure you follow the design specified on Figma for the button.

2021-08-18 09:32 UTC, dasileker approved these changes
### **Hi @den-cloud,** 

### **Project Approved 🎉✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-18 09:34 UTC, merged